# Generated by Django 5.2.7 on 2025-10-05 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ርዕስ')),
                ('content', models.TextField(verbose_name='ይዘት')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='የተለጠፈበት ቀን')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='የስብሰባ ርዕስ')),
                ('date', models.DateTimeField(verbose_name='ቀን')),
                ('location', models.CharField(max_length=255, verbose_name='ቦታ')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ሙሉ ስም')),
                ('gender', models.CharField(choices=[('M', 'ወንድ'), ('F', 'ሴት')], max_length=1, verbose_name='ጾታ')),
                ('date_of_birth', models.DateField(verbose_name='የትውልድ ቀን')),
                ('photo', models.ImageField(default='default.png', upload_to='member_photos/', verbose_name='ፎቶግራፍ')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='ስልክ ቁጥር')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='ኢሜይል')),
                ('region', models.CharField(choices=[('ADD', 'አዲስ አበባ'), ('AMH', 'አማራ'), ('ORO', 'ኦሮሚያ'), ('SID', 'ሲዳማ'), ('SOU', 'ደቡብ'), ('SOM', 'ሶማሌ'), ('TIG', 'ትግራይ'), ('GAM', 'ጋምቤላ'), ('HAR', 'ሀረሪ'), ('AFS', 'አፋር'), ('BEN', 'ቤኒሻንጉል ጉሙዝ')], max_length=3, verbose_name='ክልል')),
                ('zone', models.CharField(max_length=100, verbose_name='ዞን')),
                ('woreda', models.CharField(max_length=100, verbose_name='ወረዳ')),
                ('kebele', models.CharField(blank=True, max_length=100, null=True, verbose_name='ቀበሌ')),
                ('city', models.CharField(max_length=100, verbose_name='ከተማ')),
                ('education_level', models.CharField(choices=[('NONE', 'ትምህርት የሌለው'), ('PRIMARY', 'የመጀመሪያ ደረጃ'), ('SECONDARY', 'ሁለተኛ ደረጃ'), ('TVET', 'ቴክኒክና ሙያ'), ('DIPLOMA', 'ዲፕሎማ'), ('DEGREE', 'ዲግሪ'), ('MASTERS', 'ማስተርስ'), ('PHD', 'ዶክትሬት')], max_length=15, verbose_name='የትምህርት ደረጃ')),
                ('membership_level', models.CharField(choices=[('REGULAR', 'ተራ አባል'), ('COMMITTEE', 'የኮሚቴ አባል'), ('LEADERSHIP', 'አመራር')], default='REGULAR', max_length=15, verbose_name='የአባልነት ደረጃ')),
                ('membership_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='የአባልነት መለያ ቁጥር')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='የተመዘገበበት ቀን')),
                ('is_active', models.BooleanField(default=True, verbose_name='ንቁ አባል')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='የስርዓት ተጠቃሚ አካውንት')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='ተገኝቷል')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.meeting', verbose_name='ስብሰባ')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='አባል')),
            ],
            options={
                'unique_together': {('member', 'meeting')},
            },
        ),
    ]
