# Generated by Django

from django.db import migrations

def update_sou_to_set(apps, schema_editor):
    # የዚህን ማይግሬሽን ታሪካዊ Member ሞዴል እናገኛለን
    Member = apps.get_model('members', 'Member')
    # 'SOU' የሆኑትን በሙሉ ወደ 'SET' እንቀይራለን
    Member.objects.filter(region='SOU').update(region='SET')

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'), # እዚህ ላይ የዚህ ፋይል የቀድሞውን የማግሬሽን ፋይል ቁጥር አስገባ
    ]

    operations = [
        migrations.RunPython(update_sou_to_set),
    ]